/*Copyright (c) 2017-2018 Breakout.MX All Rights Reserved.
 This software is the confidential and proprietary information of breakout.mx You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with Breakout.MX*/
package com.digimo_pro.herokumysqldmp1.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.digimo_pro.herokumysqldmp1.Card;
import com.digimo_pro.herokumysqldmp1.Customer;


/**
 * ServiceImpl object for domain model class Customer.
 *
 * @see Customer
 */
@Service("HerokuMysqlDMP1.CustomerService")
public class CustomerServiceImpl implements CustomerService {

    private static final Logger LOGGER = LoggerFactory.getLogger(CustomerServiceImpl.class);

    @Autowired
	@Qualifier("HerokuMysqlDMP1.CardService")
	private CardService cardService;

    @Autowired
    @Qualifier("HerokuMysqlDMP1.CustomerDao")
    private WMGenericDao<Customer, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Customer, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "HerokuMysqlDMP1TransactionManager")
    @Override
	public Customer create(Customer customer) {
        LOGGER.debug("Creating a new Customer with information: {}", customer);
        Customer customerCreated = this.wmGenericDao.create(customer);
        if(customerCreated.getCards() != null) {
            for(Card card : customerCreated.getCards()) {
                card.setCustomerByCustomer(customerCreated);
                LOGGER.debug("Creating a new child Card with information: {}", card);
                cardService.create(card);
            }
        }
        return customerCreated;
    }

	@Transactional(readOnly = true, value = "HerokuMysqlDMP1TransactionManager")
	@Override
	public Customer getById(Integer customerId) throws EntityNotFoundException {
        LOGGER.debug("Finding Customer by id: {}", customerId);
        Customer customer = this.wmGenericDao.findById(customerId);
        if (customer == null){
            LOGGER.debug("No Customer found with id: {}", customerId);
            throw new EntityNotFoundException(String.valueOf(customerId));
        }
        return customer;
    }

    @Transactional(readOnly = true, value = "HerokuMysqlDMP1TransactionManager")
	@Override
	public Customer findById(Integer customerId) {
        LOGGER.debug("Finding Customer by id: {}", customerId);
        return this.wmGenericDao.findById(customerId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "HerokuMysqlDMP1TransactionManager")
	@Override
	public Customer update(Customer customer) throws EntityNotFoundException {
        LOGGER.debug("Updating Customer with information: {}", customer);
        this.wmGenericDao.update(customer);

        Integer customerId = customer.getId();

        return this.wmGenericDao.findById(customerId);
    }

    @Transactional(value = "HerokuMysqlDMP1TransactionManager")
	@Override
	public Customer delete(Integer customerId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Customer with id: {}", customerId);
        Customer deleted = this.wmGenericDao.findById(customerId);
        if (deleted == null) {
            LOGGER.debug("No Customer found with id: {}", customerId);
            throw new EntityNotFoundException(String.valueOf(customerId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "HerokuMysqlDMP1TransactionManager")
	@Override
	public Page<Customer> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Customers");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "HerokuMysqlDMP1TransactionManager")
    @Override
    public Page<Customer> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Customers");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "HerokuMysqlDMP1TransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service HerokuMysqlDMP1 for table Customer to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "HerokuMysqlDMP1TransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "HerokuMysqlDMP1TransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "HerokuMysqlDMP1TransactionManager")
    @Override
    public Page<Card> findAssociatedCards(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated cards");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("customerByCustomer.id = '" + id + "'");

        return cardService.findAll(queryBuilder.toString(), pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service CardService instance
	 */
	protected void setCardService(CardService service) {
        this.cardService = service;
    }

}

