/*Copyright (c) 2017-2018 Breakout.MX All Rights Reserved.
 This software is the confidential and proprietary information of breakout.mx You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with Breakout.MX*/

package com.digimo_pro.herokumysqldmp1.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;

@Service
public class HerokuMysqlDMP1ProcedureExecutorServiceImpl implements HerokuMysqlDMP1ProcedureExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(HerokuMysqlDMP1ProcedureExecutorServiceImpl.class);

    @Autowired
    @Qualifier("HerokuMysqlDMP1WMProcedureExecutor")
    private WMProcedureExecutor procedureExecutor;


}


