/*Copyright (c) 2017-2018 Breakout.MX All Rights Reserved.
 This software is the confidential and proprietary information of breakout.mx You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with Breakout.MX*/
package com.digimo_pro.herokumysqldmp1;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * Charge generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`charge`")
public class Charge implements Serializable {

    private Integer id;
    private String chargeid;
    private Integer amount;
    private String amtrefunded;
    private Boolean captured;
    private Timestamp created;
    private String dispute;
    private String paid;
    private String refunded;
    private String status;
    private List<Card> cards;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`CHARGEID`", nullable = true, length = 255)
    public String getChargeid() {
        return this.chargeid;
    }

    public void setChargeid(String chargeid) {
        this.chargeid = chargeid;
    }

    @Column(name = "`AMOUNT`", nullable = true, scale = 0, precision = 10)
    public Integer getAmount() {
        return this.amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    @Column(name = "`AMTREFUNDED`", nullable = true, length = 255)
    public String getAmtrefunded() {
        return this.amtrefunded;
    }

    public void setAmtrefunded(String amtrefunded) {
        this.amtrefunded = amtrefunded;
    }

    @Column(name = "`CAPTURED`", nullable = true)
    public Boolean getCaptured() {
        return this.captured;
    }

    public void setCaptured(Boolean captured) {
        this.captured = captured;
    }

    @Column(name = "`CREATED`", nullable = true)
    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Column(name = "`DISPUTE`", nullable = true, length = 255)
    public String getDispute() {
        return this.dispute;
    }

    public void setDispute(String dispute) {
        this.dispute = dispute;
    }

    @Column(name = "`PAID`", nullable = true, length = 255)
    public String getPaid() {
        return this.paid;
    }

    public void setPaid(String paid) {
        this.paid = paid;
    }

    @Column(name = "`REFUNDED`", nullable = true, length = 255)
    public String getRefunded() {
        return this.refunded;
    }

    public void setRefunded(String refunded) {
        this.refunded = refunded;
    }

    @Column(name = "`STATUS`", nullable = true, length = 255)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "charge")
    public List<Card> getCards() {
        return this.cards;
    }

    public void setCards(List<Card> cards) {
        this.cards = cards;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Charge)) return false;
        final Charge charge = (Charge) o;
        return Objects.equals(getId(), charge.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

