/*Copyright (c) 2017-2018 Breakout.MX All Rights Reserved.
 This software is the confidential and proprietary information of breakout.mx You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with Breakout.MX*/
package com.digimo_pro.herokumysqldmp1;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * Profile generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`profile`")
public class Profile implements Serializable {

    private Integer id;
    private Integer user;
    private String fname;
    private String lname;
    private String image;
    private String gender;
    private String dob;
    private String mobile;
    private String about;
    private String onlineincomelevel;
    private String proincomelevel;
    private String estatus;
    private Users users;
    private List<Card> cards;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`USER`", nullable = true, scale = 0, precision = 10)
    public Integer getUser() {
        return this.user;
    }

    public void setUser(Integer user) {
        this.user = user;
    }

    @Column(name = "`FNAME`", nullable = true, length = 255)
    public String getFname() {
        return this.fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    @Column(name = "`LNAME`", nullable = true, length = 255)
    public String getLname() {
        return this.lname;
    }

    public void setLname(String lname) {
        this.lname = lname;
    }

    @Column(name = "`IMAGE`", nullable = true, length = 255)
    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Column(name = "`GENDER`", nullable = true, length = 255)
    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @Column(name = "`DOB`", nullable = true, length = 255)
    public String getDob() {
        return this.dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    @Column(name = "`MOBILE`", nullable = true, length = 255)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name = "`ABOUT`", nullable = true, length = 255)
    public String getAbout() {
        return this.about;
    }

    public void setAbout(String about) {
        this.about = about;
    }

    @Column(name = "`ONLINEINCOMELEVEL`", nullable = true, length = 255)
    public String getOnlineincomelevel() {
        return this.onlineincomelevel;
    }

    public void setOnlineincomelevel(String onlineincomelevel) {
        this.onlineincomelevel = onlineincomelevel;
    }

    @Column(name = "`PROINCOMELEVEL`", nullable = true, length = 255)
    public String getProincomelevel() {
        return this.proincomelevel;
    }

    public void setProincomelevel(String proincomelevel) {
        this.proincomelevel = proincomelevel;
    }

    @Column(name = "`ESTATUS`", nullable = true, length = 255)
    public String getEstatus() {
        return this.estatus;
    }

    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`USER`", referencedColumnName = "`ID`", insertable = false, updatable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        if(users != null) {
            this.user = users.getId();
        }

        this.users = users;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "profileByProfile")
    public List<Card> getCards() {
        return this.cards;
    }

    public void setCards(List<Card> cards) {
        this.cards = cards;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Profile)) return false;
        final Profile profile = (Profile) o;
        return Objects.equals(getId(), profile.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

